updated workflow

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -44,7 +44,7 @@ jobs:
       INITIAL_RUST_VERSION: ''
       UPDATED_RUST_VERSION: ''
       NO_STABLE_BEFORE_EXTENSION: false
-      STABLE_AFTER_EXTENSIO: false
+      STABLE_AFTER_EXTENSION: false
     steps:
     - name: Checkout #Clones the repository to the runner
       uses: actions/checkout@v4
@@ -56,9 +56,20 @@ jobs:
       uses: dtolnay/rust-toolchain@master
       with:
         toolchain: 1.81 #Installs rust 1.81 (an outdated version) and sets that as the default toolchain
+        #Note we rely on installing this specific version of outdated rust in run_debug (see run_debug to learn more)
 
 
-    
+    #LOG output of rustc --version and save it in env varaible
+    - name: set up env var that is the initial Rust version
+      shell: bash #The default on non-Windows. Note this only impacts this step
+      run: echo "INITIAL_RUST_VERSION="$(rustc --version)"" >> $GITHUB_ENV
+    - shell: bash #The default on non-Windows. Note this only impacts this step
+      run: echo "The value of INITIAL_RUST_VERSION is ${{ env.INITIAL_RUST_VERSION }} "
+
+
+
+
+    #Asserting we do NOT have latest stable rust installed before our tests
     - name: check we do NOT have the latest stable version
       shell: bash
       # runs subcommand rustup show, checks if the output DOES NOT have
@@ -71,18 +82,13 @@ jobs:
       run: echo "The value of NO_STABLE_BEFORE_EXTENSION is ${{ env.NO_STABLE_BEFORE_EXTENSION }} "
     
     - run: rustup show #for inspection that the above command ran correctly
+      #alternative: rustup toolchain list instead of rustup show
 
     - name: Assert no latest stable installed before we run our tests
       shell: bash
-      if: ${{ env.NO_STABLE_BEFORE_EXTENSION }} == false
+      if: env.NO_STABLE_BEFORE_EXTENSION != 'true'
       run: exit 1 #causes the job to fail
-
-    #LOG output of rustc --version and save it in env varaible
-    - name: set up env var that is the initial Rust version
-      shell: bash #The default on non-Windows. Note this only impacts this step
-      run: echo "INITIAL_RUST_VERSION="$(rustc --version)"" >> $GITHUB_ENV
-    - shell: bash #The default on non-Windows. Note this only impacts this step
-      run: echo "The value of INITIAL_RUST_VERSION is ${{ env.INITIAL_RUST_VERSION }} "
+    #End of asserting we do NOT have latest stable rust installed before our tests
 
 
     #Install Node and run our tests
@@ -97,24 +103,37 @@ jobs:
       if: runner.os != 'Linux'
 
 
-    #Stable Rust should have been updated
-    - run: rustup show
+    #Stable Rust should have been updated -- We assert that now
+    - name: check we DO have the latest stable version
+      shell: bash
+      # runs subcommand rustup show, checks if the output DOES have the word stable in it.
+      #If it DOES contain stable, set the STABLE_AFTER_EXTENSION value as true
+      run: |
+        if [[ "$(rustup show)" =~ "stable" ]]; then
+        echo "STABLE_AFTER_EXTENSION=true" >> $GITHUB_ENV
+        fi
+    - shell: bash #The default on non-Windows. Note this only impacts this step
+      run: echo "The value of STABLE_AFTER_EXTENSION is ${{ env.STABLE_AFTER_EXTENSION }} "
+    
+    - run: rustup show #for inspection that the above command ran correctly
+     #alternative: rustup toolchain list instead of rustup show
 
-    #MAYBE TRY rustup toolchain list instead of rustup show (as rustup show sometimes updates rust)
-    - run: rustup toolchain list
+    - name: Assert latest stable installed after we ran our tests
+      shell: bash
+      if: env.STABLE_AFTER_EXTENSION != 'true'
+      run: exit 1 #causes the job to fail
 
-    #TODO: add assert here or something that this includes the word stable-- this is how we test
-    #the extension updated rust and not any of the following commands
-    #also duplicate this and add an assert before running our tests that it does NOT include the word stable
-    #I think you use grep for this (not sure)
+    - run: rustup show #for inspection that the above command ran correctly
+    #End of asserting stable rust updated
+
 
 
 
     #Since the default tool chain was set to the outdated version of rust, we also MUST run this
     - run: rustup default stable #this changes the default toolchain to the latest version of stable installed (apparently)
       #CRITICAL Note: this installs the latest stable version of rust (if it wasn't already installed).
-      #so we can't tell if our test worked.
-      #We need to account for this
+      #This is why we needed to assert the latest stable version was not installed before our tests
+      #AND immediatly installed after our tests.
 
 
     #check default stable is now the latest version of stable
@@ -131,5 +150,5 @@ jobs:
 
     - name: check if rust was updated (assert the env variables are not equal)
       shell: bash
-      if: ${{ env.INITIAL_RUST_VERSION == env.UPDATED_RUST_VERSION }}
+      if: env.INITIAL_RUST_VERSION == env.UPDATED_RUST_VERSION
       run: exit 1 #causes the job to fail
